require "rspec/core/rake_task"

namespace :spec do
  desc "Run the functional suite against the CLI"
  RSpec::Core::RakeTask.new(:functional, [] => [:set_path])
  
  task :set_path do
  	%w(bin lib).each do |d|
  		project_bin_dir = File.join(File.dirname(File.expand_path(__FILE__)), '..', d)
    	ENV['PATH'] = project_bin_dir + ':'+ ENV['PATH']
  	end
  end
end